image: node:latest

stages:
  - build
  - test

before_script:
  - cd client/
  - npm ci

build:
  stage: build
  script:
    - npm run build

nglint:
  stage: test
  allow_failure: false
  script:
    - npm run lint
    - cd ../server/
    - npm ci
    - npm run lint

unit_tests:
    stage: test
    image: trion/ng-cli-karma
    allow_failure: false
    script:
      - xvfb-run npm run coverage
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    tags:
      - docker