image: node:latest

stages:
  - build
  - test

build:
  stage: build
  before_script:
  - cd client/
  - npm ci
  script:
    - npm run build

variables:
  CLI_VERSION: 6.2.1

nglint:
  stage: test
  allow_failure: false
  before_script:
    - cd client/
    - npm ci
  script:
    - npm run lint
    - cd ../server/
    - npm ci
    - npm run lint

unit_tests:
    stage: test
    image: angular/ngcontainer
    allow_failure: false
    before_script:
      - xvfb-run cd client/
      - xvfb-run npm ci
    script:
      - xvfb-run npm run coverage
    coverage: '/Lines \W+: (\d+\.\d+)%.*/'
    tags:
      - docker