image: node:latest

stages:
  - build
  - test

before_script:
  - cd client/
  - npm ci

build:
  stage: build
  script:
    - npm run build

variables:
  CLI_VERSION: 6.2.1

nglint:
  stage: test
  allow_failure: false
  script:
    - npm run lint
    - cd ../server/
    - npm run lint

unit_tests:
  stage: test
  image: atlassianlabs/docker-node-jdk-chrome-firefox
  allow_failure: false
  script:
    - rm /tmp/.X99-lock
    - rm /tmp/.X100-lock
    - npm run coverage
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  tags:
    - docker