stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: trion/ng-cli
  before_script:
    - npm ci
  script:
    - ng build --prod
  tags:
    - docker
  only:
    - merge_requests

variables:
  CLI_VERSION: 6.2.1

test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
    - ng test --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - docker
  only:
    - merge_requests

test:nglint:
  stage: test
  image: trion/ng-cli:${CLI_VERSION}
  script:
    - ng lint
  tags:
    - docker