image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - cd client/
  - npm ci

build:
  stage: build
  script:
    - npm run build

variables:
  CLI_VERSION: 6.2.1

unit_tests:
  stage: test
  allow_failure: false
  script:
    - npm run test
  tags:
    - docker

nglint:
  stage: test
  allow_failure: false
  script:
    - npm run lint