image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - cd client/
    - npm ci
  script:
    - npm run build
  tags:
    - docker

variables:
  CLI_VERSION: 6.2.1

unit_tests:
  stage: test
  allow_failure: false
  script:
    - npm run test
  tags:
    - docker

nglint:
  stage: test
  script:
    - npm run lint
  tags:
    - docker