image: node:latest

cache:
  paths:
    - client/

stages:
  - build
  - test
  - deploy

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build
  tags:
    - docker

variables:
  CLI_VERSION: 6.2.1

unit_tests:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
    - npm run test
  tags:
    - docker

nglint:
  stage: test
  image: trion/ng-cli:${CLI_VERSION}
  script:
    - npm run lint
  tags:
    - docker