image: xwiillz/node-yarn-firefox-chromium:latest
cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - client/node_modules/

stages:
  - build
  - test

before_script:
  - cd client/
  - yarn

build:
  stage: build
  script:
    - yarn build

nglint:
  stage: test
  allow_failure: false
  script:
    - yarn lint

unit_tests:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - yarn coverage
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  tags:
    - docker