export enum NumericalValues {
    TITLEBAR_WIDTH = 60,
    SIDEBAR_WIDTH = 56,
    INITIAL_TRANSPARENCY = 100,
    RGBTOHEX_FACTOR = 2.55,
    COLOUR_PALETTE_SEPARATOR = 0.15,
    HEX_LENGTH = 16,
    HEX_NO_ALPHA = 7,
    DUPLICATE_OFFSET = 20,
    NOT_VALID = -1,
    ONE_EIGHTY = 180,
}
